import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'rsuite/dist/rsuite-no-reset.min.css';
import { CustomProvider } from "rsuite";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Quiz Application</title>
      <link rel="icon" type="image/x-icon" href="/Bit.png"></link>
      <body className={`${inter.className} w-full bg-white overflow-x-hidden`}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
}
