spring:
  application:
    name: PROFILE-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: bit_test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      hostname: localhost


server:
  port: 8085

custom:
  config:
    secret-key: GyBtU/YPI6O2ZwN9gjT9OJJa+IcjPux44o1A2x5cnpBUj5axi5jbxgfo6nwFWdgYX/3XRjCdn7Z4rcJ+l0DiCjcqPqvEgwTeOSKn39xGLo2i4WXDmPM1xzBJfKDzC5e1sWbjgVtotzCbzz1Dr4VRNWIDu6MG79aXBv6oM+/83BPGKIZ4mi13kqQvhyezLhW3M/0hOqbhO0oIn1zw/rlz9/lQFoukSntiI+RQSaF6TRPQ/riYDtfWhegMeM9WGyJX15ohAe02abq/ok4TM6x9kfu6YczfhSXwh7xTvcAaLfJI+nwFHwoTlkivQ3HaO4DkvFRYT8nyHwb1yeozQhtX0MfICCtsWXSC+Dg2EwqTbC6SZHtJsuOLw9Ew0FhUd+A5jqbEHC7dTIgHqzKgmx5gr/gR7ZF3CkjzdUD/4oZEHPtFGYpZQekkbGjmBxm4PUcgAD8+9ll/uG6Cxn/k1Efj7T32WHEJvaH34cFwVez2I91gvcCxeW5wWzb/Fo+j7XUYQetxA4Y8MTx218ey2apiVTdlk5LFBqE3Cfpmp6qMWj8cEmgcyZ7VYDvUm5bJ0HpkoaYgv6Spuvr9ZXUD4Hgo0Yfk1W6wL7/ypaFvACN6yFqs0Gl4MuTLReXjNEc9WGLuzKdPH7PGK9bJJbfsJVZ7MWsboZOSv/zIqJXx8pxPiePOp0SeHecEJ8UD61svU093

logging:
  level:
    org.springframework.security: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug